export type Reservation = {
  id: string;
  userId: string;
  firstName: string;
  lastName: string;
  eventId: string;
  status:
    | "pending"
    | "confirmed"
    | "cancelled"
    | "waitlist";
  createdAt: Date;
};

export const mockReservations: Reservation[] = [
  {
    id: "dsfefs",
    userId: "1",
    firstName: "Leslie",
    lastName: "Alexander",
    eventId: "1",
    status: "pending",
    createdAt: new Date("Aug. 15 2025"),
  },
  {
    id: "a2",
    userId: "2",
    firstName: "John",
    lastName: "Doe",
    eventId: "2",
    status: "confirmed",
    createdAt: new Date("Aug. 16 2025"),
  },
  {
    id: "a3",
    userId: "3",
    firstName: "Jane",
    lastName: "Smith",
    eventId: "3",
    status: "cancelled",
    createdAt: new Date("Aug. 17 2025"),
  },
  {
    id: "a4",
    userId: "4",
    firstName: "Alice",
    lastName: "Johnson",
    eventId: "4",
    status: "pending",
    createdAt: new Date("Aug. 18 2025"),
  },
  {
    id: "a5",
    userId: "5",
    firstName: "Bob",
    lastName: "Brown",
    eventId: "5",
    status: "confirmed",
    createdAt: new Date("Aug. 19 2025"),
  },
  {
    id: "a6",
    userId: "6",
    firstName: "Charlie",
    lastName: "Davis",
    eventId: "6",
    status: "cancelled",
    createdAt: new Date("Aug. 20 2025"),
  },
  {
    id: "a7",
    userId: "7",
    firstName: "Diana",
    lastName: "Evans",
    eventId: "7",
    status: "pending",
    createdAt: new Date("Aug. 21 2025"),
  },
  {
    id: "a8",
    userId: "8",
    firstName: "Ethan",
    lastName: "Foster",
    eventId: "8",
    status: "confirmed",
    createdAt: new Date("Aug. 22 2025"),
  },
  {
    id: "a9",
    userId: "9",
    firstName: "Fiona",
    lastName: "Garcia",
    eventId: "9",
    status: "cancelled",
    createdAt: new Date("Aug. 23 2025"),
  },
  {
    id: "a10",
    userId: "10",
    firstName: "George",
    lastName: "Harris",
    eventId: "10",
    status: "pending",
    createdAt: new Date("Aug. 24 2025"),
  },
  {
    id: "a11",
    userId: "11",
    firstName: "Hannah",
    lastName: "Iverson",
    eventId: "11",
    status: "confirmed",
    createdAt: new Date("Aug. 25 2025"),
  },
  {
    id: "a12",
    userId: "12",
    firstName: "Ian",
    lastName: "Jackson",
    eventId: "12",
    status: "cancelled",
    createdAt: new Date("Aug. 26 2025"),
  },
  {
    id: "a13",
    userId: "13",
    firstName: "Julia",
    lastName: "King",
    eventId: "13",
    status: "pending",
    createdAt: new Date("Aug. 27 2025"),
  },
  {
    id: "a14",
    userId: "14",
    firstName: "Kevin",
    lastName: "Lewis",
    eventId: "14",
    status: "confirmed",
    createdAt: new Date("Aug. 28 2025"),
  },
  {
    id: "a15",
    userId: "15",
    firstName: "Laura",
    lastName: "Martinez",
    eventId: "15",
    status: "cancelled",
    createdAt: new Date("Aug. 29 2025"),
  },
  {
    id: "a16",
    userId: "16",
    firstName: "Mike",
    lastName: "Nelson",
    eventId: "16",
    status: "pending",
    createdAt: new Date("Aug. 30 2025"),
  },
  {
    id: "a17",
    userId: "17",
    firstName: "Nina",
    lastName: "Owens",
    eventId: "17",
    status: "confirmed",
    createdAt: new Date("Aug. 31 2025"),
  },
  {
    id: "a18",
    userId: "18",
    firstName: "Oscar",
    lastName: "Perez",
    eventId: "18",
    status: "cancelled",
    createdAt: new Date("Sep. 1 2025"),
  },
  {
    id: "a19",
    userId: "19",
    firstName: "Paula",
    lastName: "Quinn",
    eventId: "19",
    status: "pending",
    createdAt: new Date("Sep. 2 2025"),
  },
  {
    id: "a20",
    userId: "20",
    firstName: "Quentin",
    lastName: "Roberts",
    eventId: "20",
    status: "confirmed",
    createdAt: new Date("Sep. 3 2025"),
  },
  {
    id: "a21",
    userId: "21",
    firstName: "Rachel",
    lastName: "Stewart",
    eventId: "21",
    status: "cancelled",
    createdAt: new Date("Sep. 4 2025"),
  },
  {
    id: "a22",
    userId: "22",
    firstName: "Sam",
    lastName: "Turner",
    eventId: "22",
    status: "pending",
    createdAt: new Date("Sep. 5 2025"),
  },
  {
    id: "a23",
    userId: "23",
    firstName: "Tina",
    lastName: "Underwood",
    eventId: "23",
    status: "confirmed",
    createdAt: new Date("Sep. 6 2025"),
  },
  {
    id: "a24",
    userId: "24",
    firstName: "Uma",
    lastName: "Vargas",
    eventId: "24",
    status: "cancelled",
    createdAt: new Date("Sep. 7 2025"),
  },
  {
    id: "a25",
    userId: "25",
    firstName: "Victor",
    lastName: "White",
    eventId: "25",
    status: "pending",
    createdAt: new Date("Sep. 8 2025"),
  },
  {
    id: "a26",
    userId: "26",
    firstName: "Wendy",
    lastName: "Xavier",
    eventId: "26",
    status: "confirmed",
    createdAt: new Date("Sep. 9 2025"),
  },
  {
    id: "a27",
    userId: "27",
    firstName: "Xander",
    lastName: "Young",
    eventId: "27",
    status: "cancelled",
    createdAt: new Date("Sep. 10 2025"),
  },
];
