import type { Enrollee } from "./program_tables";

type StatusType = "submitted" | "accepted" | "waitlist" | "declined";

export const mockEnrollees: Enrollee[] = [
  {
    id: "1",
    firstName: "Leslie",
    lastName: "Alexander",
    email: "leslie.alexander@example.com",
    status: "submitted",
    enrollmentDate: "Aug. 15 2025",
    appliedDate: "Aug. 1 2025",
    image: "https://randomuser.me/api/portraits/women/1.jpg",
  },
  {
    id: "2",
    firstName: "Michael",
    lastName: "Smith",
    email: "michael.smith@example.com",
    status: "accepted",
    enrollmentDate: "Aug. 16 2025",
    appliedDate: "Aug. 2 2025",
    image: "https://randomuser.me/api/portraits/men/2.jpg",
  },
  {
    id: "3",
    firstName: "Emily",
    lastName: "Johnson",
    email: "emily.johnson@example.com",
    status: "waitlist",
    enrollmentDate: "Aug. 17 2025",
    appliedDate: "Aug. 3 2025",
    image: "https://randomuser.me/api/portraits/women/3.jpg",
  },
  {
    id: "4",
    firstName: "David",
    lastName: "Williams",
    email: "david.williams@example.com",
    status: "declined",
    enrollmentDate: "Aug. 18 2025",
    appliedDate: "Aug. 4 2025",
    image: "https://randomuser.me/api/portraits/men/4.jpg",
  },
  {
    id: "5",
    firstName: "Sarah",
    lastName: "Brown",
    email: "sarah.brown@example.com",
    status: "submitted",
    enrollmentDate: "Aug. 19 2025",
    appliedDate: "Aug. 5 2025",
    image: "https://randomuser.me/api/portraits/women/5.jpg",
  },
  {
    id: "6",
    firstName: "James",
    lastName: "Jones",
    email: "james.jones@example.com",
    status: "accepted",
    enrollmentDate: "Aug. 20 2025",
    appliedDate: "Aug. 6 2025",
    image: "https://randomuser.me/api/portraits/men/6.jpg",
  },
  {
    id: "7",
    firstName: "Olivia",
    lastName: "Garcia",
    email: "olivia.garcia@example.com",
    status: "waitlist",
    enrollmentDate: "Aug. 21 2025",
    appliedDate: "Aug. 7 2025",
    image: "https://randomuser.me/api/portraits/women/7.jpg",
  },
  {
    id: "8",
    firstName: "William",
    lastName: "Martinez",
    email: "william.martinez@example.com",
    status: "declined",
    enrollmentDate: "Aug. 22 2025",
    appliedDate: "Aug. 8 2025",
    image: "https://randomuser.me/api/portraits/men/8.jpg",
  },
  {
    id: "9",
    firstName: "Sophia",
    lastName: "Hernandez",
    email: "sophia.hernandez@example.com",
    status: "submitted",
    enrollmentDate: "Aug. 23 2025",
    appliedDate: "Aug. 9 2025",
    image: "https://randomuser.me/api/portraits/women/9.jpg",
  },
  {
    id: "10",
    firstName: "Benjamin",
    lastName: "Lopez",
    email: "benjamin.lopez@example.com",
    status: "accepted",
    enrollmentDate: "Aug. 24 2025",
    appliedDate: "Aug. 10 2025",
    image: "https://randomuser.me/api/portraits/men/10.jpg",
  },
  {
    id: "11",
    firstName: "Ava",
    lastName: "Gonzalez",
    email: "ava.gonzalez@example.com",
    status: "waitlist",
    enrollmentDate: "Aug. 25 2025",
    appliedDate: "Aug. 11 2025",
    image: "https://randomuser.me/api/portraits/women/11.jpg",
  },
  {
    id: "12",
    firstName: "Lucas",
    lastName: "Wilson",
    email: "lucas.wilson@example.com",
    status: "declined",
    enrollmentDate: "Aug. 26 2025",
    appliedDate: "Aug. 12 2025",
    image: "https://randomuser.me/api/portraits/men/12.jpg",
  },
  {
    id: "13",
    firstName: "Mia",
    lastName: "Anderson",
    email: "mia.anderson@example.com",
    status: "submitted",
    enrollmentDate: "Aug. 27 2025",
    appliedDate: "Aug. 13 2025",
    image: "https://randomuser.me/api/portraits/women/13.jpg",
  },
  {
    id: "14",
    firstName: "Henry",
    lastName: "Thomas",
    email: "henry.thomas@example.com",
    status: "accepted",
    enrollmentDate: "Aug. 28 2025",
    appliedDate: "Aug. 14 2025",
    image: "https://randomuser.me/api/portraits/men/14.jpg",
  },
  {
    id: "15",
    firstName: "Charlotte",
    lastName: "Taylor",
    email: "charlotte.taylor@example.com",
    status: "waitlist",
    enrollmentDate: "Aug. 29 2025",
    appliedDate: "Aug. 15 2025",
    image: "https://randomuser.me/api/portraits/women/15.jpg",
  },
  {
    id: "16",
    firstName: "Jack",
    lastName: "Moore",
    email: "jack.moore@example.com",
    status: "declined",
    enrollmentDate: "Aug. 30 2025",
    appliedDate: "Aug. 16 2025",
    image: "https://randomuser.me/api/portraits/men/16.jpg",
  },
  {
    id: "17",
    firstName: "Amelia",
    lastName: "Jackson",
    email: "amelia.jackson@example.com",
    status: "submitted",
    enrollmentDate: "Aug. 31 2025",
    appliedDate: "Aug. 17 2025",
    image: "https://randomuser.me/api/portraits/women/17.jpg",
  },
  {
    id: "18",
    firstName: "Ethan",
    lastName: "Martin",
    email: "ethan.martin@example.com",
    status: "accepted",
    enrollmentDate: "Sep. 1 2025",
    appliedDate: "Aug. 18 2025",
    image: "https://randomuser.me/api/portraits/men/18.jpg",
  },
  {
    id: "19",
    firstName: "Harper",
    lastName: "Lee",
    email: "harper.lee@example.com",
    status: "waitlist",
    enrollmentDate: "Sep. 2 2025",
    appliedDate: "Aug. 19 2025",
    image: "https://randomuser.me/api/portraits/women/19.jpg",
  },
  {
    id: "20",
    firstName: "Alexander",
    lastName: "Perez",
    email: "alexander.perez@example.com",
    status: "declined",
    enrollmentDate: "Sep. 3 2025",
    appliedDate: "Aug. 20 2025",
    image: "https://randomuser.me/api/portraits/men/20.jpg",
  },
  {
    id: "21",
    firstName: "Ella",
    lastName: "White",
    email: "ella.white@example.com",
    status: "submitted",
    enrollmentDate: "Sep. 4 2025",
    appliedDate: "Aug. 21 2025",
    image: "https://randomuser.me/api/portraits/women/21.jpg",
  },
  {
    id: "22",
    firstName: "Daniel",
    lastName: "Harris",
    email: "daniel.harris@example.com",
    status: "accepted",
    enrollmentDate: "Sep. 5 2025",
    appliedDate: "Aug. 22 2025",
    image: "https://randomuser.me/api/portraits/men/22.jpg",
  },
  {
    id: "23",
    firstName: "Grace",
    lastName: "Clark",
    email: "grace.clark@example.com",
    status: "waitlist",
    enrollmentDate: "Sep. 6 2025",
    appliedDate: "Aug. 23 2025",
    image: "https://randomuser.me/api/portraits/women/23.jpg",
  },
  {
    id: "24",
    firstName: "Matthew",
    lastName: "Lewis",
    email: "matthew.lewis@example.com",
    status: "declined",
    enrollmentDate: "Sep. 7 2025",
    appliedDate: "Aug. 24 2025",
    image: "https://randomuser.me/api/portraits/men/24.jpg",
  },
  {
    id: "25",
    firstName: "Chloe",
    lastName: "Walker",
    email: "chloe.walker@example.com",
    status: "submitted",
    enrollmentDate: "Sep. 8 2025",
    appliedDate: "Aug. 25 2025",
    image: "https://randomuser.me/api/portraits/women/25.jpg",
  },
];
